# Generated by Django 5.1.2 on 2024-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='senha',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
